// This file is generated by Slice Machine. Update with care!

import Hero from './Hero';
import Image from './Image';
import Quote from './Quote';
import Text from './Text';
import TextWithImage from './TextWithImage';
import Video from './Video';

export {
	Hero,
	Image,
	Quote,
	Text,
	TextWithImage,
	Video,
};

export const components = {
	hero: Hero,
	image: Image,
	quote: Quote,
	text: Text,
	text_with_image: TextWithImage,
	video: Video,
};
