// This file is generated by Slice Machine. Update with care!

import Image from './Image';
import Text from './Text';
import Video from './Video';
import TextWithImage from './TextWithImage';

export {
	Image,
	Text,
	TextWithImage,
	Video,
};

export const components = {
	image: Image,
	text: Text,
	text_with_image: TextWithImage,
	video: Video,
};
